//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjerTGR_PFE_2016_Fin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Bulletins_officiel
    {
        public Bulletins_officiel()
        {
            this.Union_ref_bo = new HashSet<Union_ref_bo>();
        }
    
        public int id_bo { get; set; }
        public string name_bo { get; set; }
        public string type_bo { get; set; }
        [DisplayName(" Bulletins Officiel")]
        public string patch_bo { get; set; }
        public Nullable<int> taille_bo { get; set; }
    
        public virtual ICollection<Union_ref_bo> Union_ref_bo { get; set; }
    }
}
