//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjerTGR_PFE_2016_Fin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Categorie
    {
        public Categorie()
        {
            this.Corps = new HashSet<Corps>();
            this.Union_ref_bo = new HashSet<Union_ref_bo>();
        }


        public int id_catg { get; set; }

     
        [DisplayName("Numéro Categorie")]
        public int Num_catg { get; set; }

 
        [DisplayName(" Categorie")]
        public string Nom_catg { get; set; }

    
        public virtual ICollection<Corps> Corps { get; set; }
        public virtual ICollection<Union_ref_bo> Union_ref_bo { get; set; }
    }
}
