//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjerTGR_PFE_2016_Fin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Corps
    {
        public Corps()
        {
            this.Grade = new HashSet<Grade>();
            this.Union_ref_bo = new HashSet<Union_ref_bo>();
        }
    
        public int id_corp { get; set; }

        [Required]
        [DisplayName(" Numéro Corps")]
        public int Num_corp { get; set; }

         [Required]
         [DisplayName(" Corps")]
        public string Nom_corp { get; set; }
        public Nullable<int> id_catg { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual ICollection<Grade> Grade { get; set; }
        public virtual ICollection<Union_ref_bo> Union_ref_bo { get; set; }
    }
}
