//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjerTGR_PFE_2016_Fin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Base_Final_TGR2016Entities1 : DbContext
    {
        public Base_Final_TGR2016Entities1()
            : base("name=Base_Final_TGR2016Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bulletins_officiel> Bulletins_officiel { get; set; }
        public DbSet<Categorie> Categorie { get; set; }
        public DbSet<Corps> Corps { get; set; }
        public DbSet<Grade> Grade { get; set; }
        public DbSet<Note_Parametrage> Note_Parametrage { get; set; }
        public DbSet<Union_ref_bo> Union_ref_bo { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
