//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjerTGR_PFE_2016_Fin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Note_Parametrage
    {
        public Note_Parametrage()
        {
            this.Union_ref_bo = new HashSet<Union_ref_bo>();
        }
    
        public int id_par { get; set; }
        public string name_par { get; set; }
        public string type_par { get; set; }
         [DisplayName(" Note_Parametrage")]
        public string patch_par { get; set; }
        public Nullable<int> taille_par { get; set; }
    
        public virtual ICollection<Union_ref_bo> Union_ref_bo { get; set; }
    }
}
