//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjerTGR_PFE_2016_Fin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Union_ref_bo
    {
        public int id_un { get; set; }
        [DisplayName("Numéro BO")]
        public Nullable<int> Num_bo { get; set; }
        public Nullable<int> id_bo { get; set; }
        public Nullable<int> id_par { get; set; }
        public Nullable<int> id_catg { get; set; }
        public Nullable<int> id_corp { get; set; }
        public Nullable<int> id_grad { get; set; }
    
        public virtual Bulletins_officiel Bulletins_officiel { get; set; }
        public virtual Categorie Categorie { get; set; }
        public virtual Corps Corps { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual Note_Parametrage Note_Parametrage { get; set; }
    }
}
